/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * config.java
 *
 * Created on 16/08/2014, 17:03:24
 */

package samdir_gui;

import java.awt.Color;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.FileReader;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.io.OutputStreamWriter;
import java.util.Iterator;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Set;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;
import org.jdesktop.swingx.util.PaintUtils;

/**
 *
 * @author Administrador
 */
public class config extends javax.swing.JFrame {

    Color colorNivel7;
    Color colorNivelRojo3;
    String directory = ".archivos";
    String filename = "formdata.os";
    String fileNamePerfil;
    String filenameIn = "input.txt";
    String filenameOut = "output.txt";
    private String pName = "samdir";
    FileFilter filter = new FileNameExtensionFilter("Archivos .dat", new String[] {"dat"});
    private LinkedHashMap hMap = new LinkedHashMap();
    Property properties;
    /** Creates new form config */
    public config() {
    Color color;
        
        initComponents();
        initDevices();
        File file = new File(directory);
        if(!file.exists()){
            new File(directory).mkdir();
        }
        
        colorNivel7 = new Color(204, 255, 0);
        nivelVerde7.setBackground(PaintUtils.setAlpha(colorNivel7, 100)); 
        nivelVerde7.setOpaque(true);
        nivelVerde8.setBackground(PaintUtils.setAlpha(colorNivel7, 100)); 
        nivelVerde8.setOpaque(true);
        color = new Color(255, 255, 102);
        nivelAmarillo1.setBackground(PaintUtils.setAlpha(color, 100)); 
        nivelAmarillo1.setOpaque(true);
        nivelAmarillo2.setBackground(PaintUtils.setAlpha(color, 100)); 
        nivelAmarillo2.setOpaque(true);
        color = new Color(255, 255, 0);
        nivelAmarillo3.setBackground(PaintUtils.setAlpha(color, 100)); 
        nivelAmarillo3.setOpaque(true);
        color = new Color(255, 204, 0);
        nivelRojo1.setBackground(PaintUtils.setAlpha(color, 100)); 
        nivelRojo1.setOpaque(true);
        color = new Color(255, 153, 0);
        nivelRojo2.setBackground(PaintUtils.setAlpha(color, 100)); 
        nivelRojo2.setOpaque(true);
        colorNivelRojo3 = new Color(255, 0, 0);
        nivelRojo3.setBackground(PaintUtils.setAlpha(colorNivelRojo3, 100)); 
        nivelRojo3.setOpaque(true);
        // nivelVerde8.setOpaque(false);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jXTaskPane1 = new org.jdesktop.swingx.JXTaskPane();
        jLabel1 = new javax.swing.JLabel();
        usuario = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        equipos = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        comentario = new javax.swing.JTextField();
        jXTaskPane2 = new org.jdesktop.swingx.JXTaskPane();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jXTaskPane3 = new org.jdesktop.swingx.JXTaskPane();
        jLabel4 = new javax.swing.JLabel();
        comboTipoSeñal = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        comboDuracionSeñal = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        freqInicial = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        freqFinal = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        stopMargin = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        repeticiones = new javax.swing.JTextField();
        jXTaskPane4 = new org.jdesktop.swingx.JXTaskPane();
        jLabel10 = new javax.swing.JLabel();
        comboVentana = new javax.swing.JComboBox();
        jLabel11 = new javax.swing.JLabel();
        inicioVentana = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        finVentana = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        comboDispositivoIn = new javax.swing.JComboBox();
        jLabel15 = new javax.swing.JLabel();
        comboDispositivoOut = new javax.swing.JComboBox();
        jLabel16 = new javax.swing.JLabel();
        comboFrecuenciaMuestreo = new javax.swing.JComboBox();
        jLabel17 = new javax.swing.JLabel();
        comboResolucion = new javax.swing.JComboBox();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        medirSNRBoton = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        nivelSalidaSlider = new javax.swing.JSlider();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        panelNiveles = new javax.swing.JPanel();
        nivelVerde1 = new javax.swing.JPanel();
        nivelVerde2 = new javax.swing.JPanel();
        nivelVerde3 = new javax.swing.JPanel();
        nivelVerde4 = new javax.swing.JPanel();
        nivelVerde5 = new javax.swing.JPanel();
        nivelVerde6 = new javax.swing.JPanel();
        nivelVerde7 = new javax.swing.JPanel();
        nivelVerde8 = new javax.swing.JPanel();
        nivelAmarillo1 = new javax.swing.JPanel();
        nivelAmarillo2 = new javax.swing.JPanel();
        nivelAmarillo3 = new javax.swing.JPanel();
        nivelRojo1 = new javax.swing.JPanel();
        nivelRojo2 = new javax.swing.JPanel();
        nivelRojo3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        guardar = new javax.swing.JButton();
        cargar = new javax.swing.JButton();
        salir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Samdir - Configuración");
        setMaximumSize(new java.awt.Dimension(2147483647, 505));
        getContentPane().setLayout(new org.jdesktop.swingx.VerticalLayout());

        jXTaskPane1.setTitle("Perfil");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Usuario");

        usuario.setName("usuario"); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Equipos");

        equipos.setName("equipos"); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Comentarios");

        comentario.setName("comentarios"); // NOI18N

        javax.swing.GroupLayout jXTaskPane1Layout = new javax.swing.GroupLayout(jXTaskPane1.getContentPane());
        jXTaskPane1.getContentPane().setLayout(jXTaskPane1Layout);
        jXTaskPane1Layout.setHorizontalGroup(
            jXTaskPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jXTaskPane1Layout.createSequentialGroup()
                .addGroup(jXTaskPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jXTaskPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jXTaskPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(comentario, javax.swing.GroupLayout.DEFAULT_SIZE, 352, Short.MAX_VALUE)
                    .addComponent(usuario)
                    .addComponent(equipos))
                .addGap(0, 0, 0))
        );
        jXTaskPane1Layout.setVerticalGroup(
            jXTaskPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jXTaskPane1Layout.createSequentialGroup()
                .addGroup(jXTaskPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jXTaskPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(equipos, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jXTaskPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comentario, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0))
        );

        getContentPane().add(jXTaskPane1);

        jXTaskPane2.setTitle("Configuración Avanzada");
        jXTaskPane2.getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        jPanel1.setLayout(new org.jdesktop.swingx.VerticalLayout());

        jXTaskPane3.setTitle("Señal de Excitación");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Tipo");

        comboTipoSeñal.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Barrido Senoidal Lineal", "Barrido Senoidal Logarítmico", "Tono Senoidal", "Tono Cosenoidal" }));
        comboTipoSeñal.setSelectedIndex(1);
        comboTipoSeñal.setName("tipo"); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Duración");

        comboDuracionSeñal.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0.682667", "1.36533", "2.73067", "5.46133", "10.9227", "21.8453" }));
        comboDuracionSeñal.setName("duracion"); // NOI18N

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Frecuencia Inicial");

        freqInicial.setText("22");
        freqInicial.setName("freqInicial"); // NOI18N

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("Frecuencia Final");

        freqFinal.setText("22000");
        freqFinal.setName("freqFinal"); // NOI18N

        jLabel8.setText("Hz");

        jLabel9.setText("Hz");

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel18.setText("Silencio");

        stopMargin.setText("0");
        stopMargin.setName("stopMargin"); // NOI18N

        jLabel19.setText("seg.");

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel22.setText("Repeticiones");

        repeticiones.setText("1");
        repeticiones.setName("repeticiones"); // NOI18N

        javax.swing.GroupLayout jXTaskPane3Layout = new javax.swing.GroupLayout(jXTaskPane3.getContentPane());
        jXTaskPane3.getContentPane().setLayout(jXTaskPane3Layout);
        jXTaskPane3Layout.setHorizontalGroup(
            jXTaskPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jXTaskPane3Layout.createSequentialGroup()
                .addGroup(jXTaskPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jXTaskPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jXTaskPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(comboTipoSeñal, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboDuracionSeñal, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jXTaskPane3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jXTaskPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(freqInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(freqFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(stopMargin, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(repeticiones, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jXTaskPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 0, 0))
        );
        jXTaskPane3Layout.setVerticalGroup(
            jXTaskPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jXTaskPane3Layout.createSequentialGroup()
                .addGroup(jXTaskPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboTipoSeñal, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jXTaskPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(comboDuracionSeñal, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jXTaskPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(freqInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(13, 13, 13)
                .addGroup(jXTaskPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(freqFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jXTaskPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(stopMargin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jXTaskPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(repeticiones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0))
        );

        jPanel1.add(jXTaskPane3);

        jXTaskPane4.setTitle("Ventana en el tiempo");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setText("Tipo de Ventana");

        comboVentana.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Hann", "Hamming", "Flat Top", "Blackman", "Bartlett", "Bartlett-Hann", "Blackman-Harris", "Bohman", "Chebyshev", "Gaussian", "Kaiser", "Nuttan", "Parzen", "Rectangular", "Taylor", "Tukey", "Triangular" }));
        comboVentana.setName("tipoVentana"); // NOI18N

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setText("Inicio");

        inicioVentana.setText("0.1");
        inicioVentana.setName("inicioVentana"); // NOI18N

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel12.setText("Fin");

        finVentana.setText("0.1");
        finVentana.setName("finVentana"); // NOI18N

        jLabel20.setText("seg.");

        jLabel21.setText("seg.");

        javax.swing.GroupLayout jXTaskPane4Layout = new javax.swing.GroupLayout(jXTaskPane4.getContentPane());
        jXTaskPane4.getContentPane().setLayout(jXTaskPane4Layout);
        jXTaskPane4Layout.setHorizontalGroup(
            jXTaskPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jXTaskPane4Layout.createSequentialGroup()
                .addGroup(jXTaskPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jXTaskPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)))
                .addGroup(jXTaskPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jXTaskPane4Layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(jLabel13))
                    .addGroup(jXTaskPane4Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(jXTaskPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(inicioVentana, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(finVentana, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboVentana, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jXTaskPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel21)
                            .addComponent(jLabel20))))
                .addGap(0, 0, 0))
        );
        jXTaskPane4Layout.setVerticalGroup(
            jXTaskPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jXTaskPane4Layout.createSequentialGroup()
                .addGroup(jXTaskPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboVentana, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jXTaskPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inicioVentana, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jXTaskPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(finVentana, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21))
                .addContainerGap())
        );

        jPanel1.add(jXTaskPane4);

        jTabbedPane1.addTab("General", jPanel1);

        jPanel2.setBackground(new java.awt.Color(214, 223, 247));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel14.setText("Dispositivo de Entrada");

        comboDispositivoIn.setName("inputDeviceName"); // NOI18N

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel15.setText("Dispositivo de Salida");

        comboDispositivoOut.setName("outputDeviceName"); // NOI18N

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel16.setText("Frecuencia de Muestreo");

        comboFrecuenciaMuestreo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "44100", "48000", "88200", "96000" }));
        comboFrecuenciaMuestreo.setSelectedIndex(1);
        comboFrecuenciaMuestreo.setName("samplingRate"); // NOI18N
        comboFrecuenciaMuestreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboFrecuenciaMuestreoActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel17.setText("Resolución");

        comboResolucion.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "16", "20", "24", "32" }));
        comboResolucion.setName("nBits"); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(comboDispositivoIn, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(53, 53, 53))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, 0)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(comboDispositivoOut, 0, 222, Short.MAX_VALUE)
                            .addComponent(comboFrecuenciaMuestreo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(comboResolucion, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboDispositivoIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboDispositivoOut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboFrecuenciaMuestreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(comboResolucion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        jTabbedPane1.addTab("I/O", jPanel2);

        jPanel3.setBackground(new java.awt.Color(214, 223, 247));

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "SNR", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 10), new java.awt.Color(51, 102, 255))); // NOI18N

        medirSNRBoton.setText("Medir");
        medirSNRBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                medirSNRBotonActionPerformed(evt);
            }
        });

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel23.setText("INR");

        jLabel24.setText("[dB]");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(medirSNRBoton))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel23)))
                .addGap(8, 8, 8)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel24)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(medirSNRBoton)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        nivelSalidaSlider.setMajorTickSpacing(25);
        nivelSalidaSlider.setMinorTickSpacing(5);
        nivelSalidaSlider.setOrientation(javax.swing.JSlider.VERTICAL);
        nivelSalidaSlider.setPaintLabels(true);
        nivelSalidaSlider.setPaintTicks(true);
        nivelSalidaSlider.setToolTipText("");
        nivelSalidaSlider.setValue(50);
        nivelSalidaSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                nivelSalidaSliderStateChanged(evt);
            }
        });

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel25.setText("Nivel de Salida");

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel26.setText("Nivel de Entrada");

        panelNiveles.setBackground(new java.awt.Color(214, 223, 247));

        nivelVerde1.setBackground(new java.awt.Color(0, 153, 0));
        nivelVerde1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        nivelVerde1.setPreferredSize(new java.awt.Dimension(2, 8));

        javax.swing.GroupLayout nivelVerde1Layout = new javax.swing.GroupLayout(nivelVerde1);
        nivelVerde1.setLayout(nivelVerde1Layout);
        nivelVerde1Layout.setHorizontalGroup(
            nivelVerde1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );
        nivelVerde1Layout.setVerticalGroup(
            nivelVerde1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 6, Short.MAX_VALUE)
        );

        nivelVerde2.setBackground(new java.awt.Color(51, 204, 0));
        nivelVerde2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout nivelVerde2Layout = new javax.swing.GroupLayout(nivelVerde2);
        nivelVerde2.setLayout(nivelVerde2Layout);
        nivelVerde2Layout.setHorizontalGroup(
            nivelVerde2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );
        nivelVerde2Layout.setVerticalGroup(
            nivelVerde2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 6, Short.MAX_VALUE)
        );

        nivelVerde3.setBackground(new java.awt.Color(0, 255, 0));
        nivelVerde3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout nivelVerde3Layout = new javax.swing.GroupLayout(nivelVerde3);
        nivelVerde3.setLayout(nivelVerde3Layout);
        nivelVerde3Layout.setHorizontalGroup(
            nivelVerde3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );
        nivelVerde3Layout.setVerticalGroup(
            nivelVerde3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 6, Short.MAX_VALUE)
        );

        nivelVerde4.setBackground(new java.awt.Color(153, 255, 0));
        nivelVerde4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout nivelVerde4Layout = new javax.swing.GroupLayout(nivelVerde4);
        nivelVerde4.setLayout(nivelVerde4Layout);
        nivelVerde4Layout.setHorizontalGroup(
            nivelVerde4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );
        nivelVerde4Layout.setVerticalGroup(
            nivelVerde4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 6, Short.MAX_VALUE)
        );

        nivelVerde5.setBackground(new java.awt.Color(153, 255, 0));
        nivelVerde5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout nivelVerde5Layout = new javax.swing.GroupLayout(nivelVerde5);
        nivelVerde5.setLayout(nivelVerde5Layout);
        nivelVerde5Layout.setHorizontalGroup(
            nivelVerde5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );
        nivelVerde5Layout.setVerticalGroup(
            nivelVerde5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 6, Short.MAX_VALUE)
        );

        nivelVerde6.setBackground(new java.awt.Color(204, 255, 0));
        nivelVerde6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout nivelVerde6Layout = new javax.swing.GroupLayout(nivelVerde6);
        nivelVerde6.setLayout(nivelVerde6Layout);
        nivelVerde6Layout.setHorizontalGroup(
            nivelVerde6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );
        nivelVerde6Layout.setVerticalGroup(
            nivelVerde6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 6, Short.MAX_VALUE)
        );

        nivelVerde7.setBackground(new java.awt.Color(204, 255, 0));
        nivelVerde7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout nivelVerde7Layout = new javax.swing.GroupLayout(nivelVerde7);
        nivelVerde7.setLayout(nivelVerde7Layout);
        nivelVerde7Layout.setHorizontalGroup(
            nivelVerde7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );
        nivelVerde7Layout.setVerticalGroup(
            nivelVerde7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 6, Short.MAX_VALUE)
        );

        nivelVerde8.setBackground(new java.awt.Color(204, 255, 0));
        nivelVerde8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout nivelVerde8Layout = new javax.swing.GroupLayout(nivelVerde8);
        nivelVerde8.setLayout(nivelVerde8Layout);
        nivelVerde8Layout.setHorizontalGroup(
            nivelVerde8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );
        nivelVerde8Layout.setVerticalGroup(
            nivelVerde8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 6, Short.MAX_VALUE)
        );

        nivelAmarillo1.setBackground(new java.awt.Color(255, 255, 102));
        nivelAmarillo1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout nivelAmarillo1Layout = new javax.swing.GroupLayout(nivelAmarillo1);
        nivelAmarillo1.setLayout(nivelAmarillo1Layout);
        nivelAmarillo1Layout.setHorizontalGroup(
            nivelAmarillo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );
        nivelAmarillo1Layout.setVerticalGroup(
            nivelAmarillo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 6, Short.MAX_VALUE)
        );

        nivelAmarillo2.setBackground(new java.awt.Color(255, 255, 102));
        nivelAmarillo2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout nivelAmarillo2Layout = new javax.swing.GroupLayout(nivelAmarillo2);
        nivelAmarillo2.setLayout(nivelAmarillo2Layout);
        nivelAmarillo2Layout.setHorizontalGroup(
            nivelAmarillo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );
        nivelAmarillo2Layout.setVerticalGroup(
            nivelAmarillo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 6, Short.MAX_VALUE)
        );

        nivelAmarillo3.setBackground(new java.awt.Color(255, 255, 0));
        nivelAmarillo3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout nivelAmarillo3Layout = new javax.swing.GroupLayout(nivelAmarillo3);
        nivelAmarillo3.setLayout(nivelAmarillo3Layout);
        nivelAmarillo3Layout.setHorizontalGroup(
            nivelAmarillo3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );
        nivelAmarillo3Layout.setVerticalGroup(
            nivelAmarillo3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 6, Short.MAX_VALUE)
        );

        nivelRojo1.setBackground(new java.awt.Color(255, 204, 0));
        nivelRojo1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout nivelRojo1Layout = new javax.swing.GroupLayout(nivelRojo1);
        nivelRojo1.setLayout(nivelRojo1Layout);
        nivelRojo1Layout.setHorizontalGroup(
            nivelRojo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );
        nivelRojo1Layout.setVerticalGroup(
            nivelRojo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 6, Short.MAX_VALUE)
        );

        nivelRojo2.setBackground(new java.awt.Color(255, 153, 0));
        nivelRojo2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout nivelRojo2Layout = new javax.swing.GroupLayout(nivelRojo2);
        nivelRojo2.setLayout(nivelRojo2Layout);
        nivelRojo2Layout.setHorizontalGroup(
            nivelRojo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );
        nivelRojo2Layout.setVerticalGroup(
            nivelRojo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 6, Short.MAX_VALUE)
        );

        nivelRojo3.setBackground(new java.awt.Color(255, 0, 0));
        nivelRojo3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout nivelRojo3Layout = new javax.swing.GroupLayout(nivelRojo3);
        nivelRojo3.setLayout(nivelRojo3Layout);
        nivelRojo3Layout.setHorizontalGroup(
            nivelRojo3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );
        nivelRojo3Layout.setVerticalGroup(
            nivelRojo3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 6, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panelNivelesLayout = new javax.swing.GroupLayout(panelNiveles);
        panelNiveles.setLayout(panelNivelesLayout);
        panelNivelesLayout.setHorizontalGroup(
            panelNivelesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNivelesLayout.createSequentialGroup()
                .addGroup(panelNivelesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nivelRojo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nivelRojo3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nivelRojo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nivelAmarillo3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nivelAmarillo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nivelAmarillo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nivelVerde8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nivelVerde7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nivelVerde6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nivelVerde5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nivelVerde4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nivelVerde3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nivelVerde2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nivelVerde1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panelNivelesLayout.setVerticalGroup(
            panelNivelesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNivelesLayout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(nivelRojo3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(nivelRojo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(nivelRojo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(nivelAmarillo3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(nivelAmarillo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(nivelAmarillo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(nivelVerde8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(nivelVerde7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(nivelVerde6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(nivelVerde5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(nivelVerde4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(nivelVerde3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(nivelVerde2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(nivelVerde1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54)
                        .addComponent(nivelSalidaSlider, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addGap(226, 226, 226)
                        .addComponent(jLabel25)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel26)
                        .addContainerGap(44, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(panelNiveles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(72, 72, 72))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel26))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel25)))
                .addGap(0, 0, 0)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelNiveles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(nivelSalidaSlider, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, 0))
        );

        jTabbedPane1.addTab("Niveles de Audio", jPanel3);

        jXTaskPane2.getContentPane().add(jTabbedPane1);

        getContentPane().add(jXTaskPane2);

        guardar.setText("Guardar");
        guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarActionPerformed(evt);
            }
        });

        cargar.setText("Cargar");
        cargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cargarActionPerformed(evt);
            }
        });

        salir.setText("Salir");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(201, Short.MAX_VALUE)
                .addComponent(guardar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cargar, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74)
                .addComponent(salir, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(guardar)
                    .addComponent(cargar)
                    .addComponent(salir))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel4);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarActionPerformed
        // TODO add your handling code here:
        
        cargarDatos();
        JFileChooser chooser = new JFileChooser();
      
        chooser.setFileFilter(filter);
        chooser.setAcceptAllFileFilterUsed(false);
        int resp = chooser.showSaveDialog(this);
            if (resp==JFileChooser.APPROVE_OPTION) {
                File abrir =chooser.getSelectedFile();
                fileNamePerfil = abrir.getPath();
                save(hMap, fileNamePerfil);
                
            }
            else if (resp==JFileChooser.CANCEL_OPTION) {

                    JOptionPane.showMessageDialog(null,"Se pulsó la opción Cancelar");           
                }  
        botonGuardarCls.setTrigger(evt.getActionCommand());
    }//GEN-LAST:event_guardarActionPerformed

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        // TODO add your handling code here:
        cargarDatos();
        botonSalirCls.setTrigger(evt.getActionCommand());
    }//GEN-LAST:event_salirActionPerformed

    private void comboFrecuenciaMuestreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboFrecuenciaMuestreoActionPerformed
        // TODO add your handling code here:
        javax.swing.JComboBox cb = (javax.swing.JComboBox)evt.getSource();
        String petName = (String)cb.getSelectedItem();
        float samplingRate = Integer.valueOf(petName);
        float duracion;
        int samples;
    
        comboDuracionSeñal.removeAllItems();
        for(int i = 15; i <= 20; i++){
             samples = (int) Math.pow(2, i);
             duracion =  samples /samplingRate;
             String formato = String.format("%.6g%n", duracion);
             comboDuracionSeñal.addItem(formato);
        }
        
    }//GEN-LAST:event_comboFrecuenciaMuestreoActionPerformed

    private void cargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cargarActionPerformed
        JFileChooser file = new JFileChooser();
        file.setFileFilter(filter);
        file.setAcceptAllFileFilterUsed(false);
        int resp = file.showOpenDialog(this);
        File abrir =file.getSelectedFile();
        
                
        if(abrir !=null){
               
                 if (resp==JFileChooser.APPROVE_OPTION) {
                    
                    properties = new Property(abrir.getPath(), pName);
                    properties.load();
                    if (properties.match(hMap))
                        cargarPerfil(properties);
                    else
                        JOptionPane.showMessageDialog(null,"No se encuentran las propiedades, cargue un archivo correcto"); 
                    
                } else if (resp==JFileChooser.CANCEL_OPTION) {

                   // JOptionPane.showMessageDialog(null,"Se pulsó la opción Cancelar");           
                }       
        }
      
    }//GEN-LAST:event_cargarActionPerformed
      
  
    private void medirSNRBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_medirSNRBotonActionPerformed
        // TODO add your handling code here:
        //vumetroNivel.setMinimum(0);
        //vumetroNivel.setMaximum(100);
       // vumetroNivel.setOpaque(false);
      //  vumetroNivel.setBorderPainted(false);
       
       // vumetroNivel.setForeground(Color.LIGHT_GRAY);
      //  vumetroNivel.setBackground(Color.black);
      //  vumetroNivel.setForeground(Color.green.darker());
    
      
     Thread t = new Thread() {
 
            public void run() {
                int i = 0;
                while (i <= 100) {
        //            vumetroNivel.setValue(i);
                    if(i    > 80)
                    
         //           vumetroNivel.setBackground(Color.red);
                    
                    try {
                        sleep(90);
                    } catch (InterruptedException ex) {
                        
                    }
                    i++;
                }
            }
        };
        t.start();
    }//GEN-LAST:event_medirSNRBotonActionPerformed

    private void nivelSalidaSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_nivelSalidaSliderStateChanged
        // TODO add your handling code here:
        javax.swing.JSlider source = (javax.swing.JSlider)evt.getSource();
        if (!source.getValueIsAdjusting()) {
	    int fps = (int)((javax.swing.JSlider)evt.getSource()).getValue();
	    if (fps  > 80) {
                    nivelVerde7.setBackground(colorNivel7); 
                    nivelVerde8.setBackground(colorNivel7); 
                                      
                    nivelRojo3.setBackground(colorNivelRojo3); 
                   
	    } else {
	  
	    }
        }   
    }//GEN-LAST:event_nivelSalidaSliderStateChanged

    private void cargarPerfil(Property properties){
        
        usuario.removeAll();
        usuario.setText(properties.getString(usuario.getName()));
        equipos.removeAll();
        equipos.setText(properties.getString(equipos.getName()));
        comentario.removeAll();
        comentario.setText(properties.getString(comentario.getName()));
        comboTipoSeñal.setSelectedItem(properties.getString(comboTipoSeñal.getName()));
        comboDuracionSeñal.setSelectedItem(properties.getDouble(comboDuracionSeñal.getName()));
        freqInicial.removeAll();
        freqInicial.setText(properties.getString(freqInicial.getName()));
        freqFinal.removeAll();
        freqFinal.setText(properties.getString(freqFinal.getName()));
        stopMargin.removeAll();
        stopMargin.setText(properties.getString(stopMargin.getName()));
        repeticiones.removeAll();
        repeticiones.setText(properties.getString(repeticiones.getName()));
        comboVentana.setSelectedItem(properties.getDouble(comboVentana.getName()));
        inicioVentana.removeAll();
        inicioVentana.setText(properties.getString(inicioVentana.getName()));
        finVentana.removeAll();
        finVentana.setText(properties.getString(finVentana.getName()));
        comboFrecuenciaMuestreo.setSelectedItem(properties.getDouble(comboFrecuenciaMuestreo.getName()));
        comboResolucion.setSelectedItem(properties.getDouble(comboResolucion.getName()));
        rebuild(properties);
    }
    
    public void rebuild(Property newMap) {
        hMap.clear();
        hMap.putAll(newMap.getHasMap());      
    }
    
        // Save data from LinkedHashMap to file
    public void save(LinkedHashMap<String, Object> properties,String filenamePerfil) {
        BufferedWriter bw = null;
        try {
            // Construct the BufferedWriter object
            bw = new BufferedWriter(new OutputStreamWriter(new FileOutputStream(filenamePerfil),"UTF-8"));
            bw.write("# "+pName+" Properties File");
            bw.newLine();
 
            // Save all the properties one at a time, only if there's data to write
            if (properties.size() > 0) {
                // Grab all the entries and create an iterator to run through them all
                Set<?> set = properties.entrySet();
                Iterator<?> i = set.iterator();
 
                // While there's data to iterate through..
                while (i.hasNext()) {
                    // Map the entry and save the key and value as variables
                    Map.Entry<?, ?> me = (Map.Entry<?, ?>)i.next();
                    String key = (String)me.getKey();
                    String val = me.getValue().toString();
 
                    // If it starts with "#", it's a comment so write it as such
                    if (key.charAt(0) == '#') {
                        // Writing a comment to the file
                        bw.write("# "+val);
                        bw.newLine();
                    } else {
                        // Otherwise write the key and value pair as key=value
                        bw.write(key+'='+val);
                        bw.newLine();
                    }
                }
            }
        } catch (FileNotFoundException ex) {
            System.out.println("No found file");
            
            return;
        } catch (IOException ex) {
            System.out.println("Unable to save");
            
            return;
        } finally {
            // Close the BufferedWriter
            try {
                if (bw != null) bw.close();
            } catch (IOException ex) {
                System.out.println("Unable to save");
            }
        }
    }
    
    private void cargarDatos(){
        hMap.put(usuario.getName(), usuario.getText());
        hMap.put(equipos.getName(), equipos.getText());
        hMap.put(comentario.getName(), comentario.getText());
        hMap.put(comboTipoSeñal.getName(), comboTipoSeñal.getSelectedItem().toString());
        hMap.put(comboDuracionSeñal.getName(), Double.valueOf(comboDuracionSeñal.getSelectedItem().toString()));
        hMap.put(freqInicial.getName(), Integer.valueOf(freqInicial.getText()));
        hMap.put(freqFinal.getName(), Integer.valueOf(freqFinal.getText()));
        hMap.put(stopMargin.getName(), Integer.valueOf(stopMargin.getText()));
        hMap.put(repeticiones.getName(), Integer.valueOf(repeticiones.getText()));
        hMap.put(comboVentana.getName(), comboVentana.getSelectedItem().toString());
        hMap.put(inicioVentana.getName(), Double.valueOf(inicioVentana.getText()));
        hMap.put(finVentana.getName(), Double.valueOf(finVentana.getText()));
        hMap.put(comboDispositivoIn.getName(), comboDispositivoIn.getSelectedItem().toString());
        hMap.put(comboDispositivoOut.getName(), comboDispositivoOut.getSelectedItem().toString());
        hMap.put(comboFrecuenciaMuestreo.getName(), Integer.valueOf(comboFrecuenciaMuestreo.getSelectedItem().toString()));
        hMap.put(comboResolucion.getName(), Integer.valueOf(comboResolucion.getSelectedItem().toString()));
        WriterObject(hMap);
    }
    
    public void WriterObject(Object obj){
        try{
            String strFilename = directory + "\\" + filename;
               FileOutputStream fileOut = new FileOutputStream(strFilename);
	       ObjectOutputStream out = new ObjectOutputStream(fileOut);
	       out.writeObject(obj);
	       out.close();
        }catch(IOException ex){
            ex.printStackTrace();
        }
    }
    
    public Object ReadObject() {
    Object obj = null;
    String strFilename = directory + "\\" + filename;

        try {
            File file = new File(strFilename);
         // Read object only if file exist
            if (file.exists()) {
                ObjectInputStream in = new ObjectInputStream(new
                FileInputStream(strFilename));
		obj = in.readObject();
		in.close();
            }
	}catch (IOException ex) {
		ex.printStackTrace();
	}catch (ClassNotFoundException cexp) {
		cexp.printStackTrace();
	}

    return obj;
    }
    
    public void initDevices(){
        
        String strFilenameIn = directory + "\\" + filenameIn;
        String strFilenameOut = directory + "\\" + filenameOut;
        File fileIn = new File(strFilenameIn);
        File fileOut = new File(strFilenameOut);
        BufferedReader entrada;
        try {
            entrada = new BufferedReader( new FileReader(fileIn) );
            String linea;
            while(entrada.ready()){
                linea = entrada.readLine();
               
                if(linea.contains("0) Micr?"))
                    linea = linea.replaceFirst("Micr?", "Micrófono (Dispositivo de High");
                
                comboDispositivoIn.addItem(linea);
            }
        } catch (IOException ex) {
            ex.printStackTrace();
        }
          try {
            entrada = new BufferedReader( new FileReader(fileOut) );
            String linea;
            while(entrada.ready()){
                linea = entrada.readLine();
                if(linea.contains("0) Micr?")){
                    linea = linea.replaceFirst("Micr?", "Altavoces (Dispositivo de High");
                }
                comboDispositivoOut.addItem(linea);
            }
        } catch (IOException ex) {
            ex.printStackTrace();
        }
    }
            
    
    /**
    * @param args the command line arguments
    
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new config().setVisible(true);
            }
        });
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cargar;
    private javax.swing.JComboBox comboDispositivoIn;
    private javax.swing.JComboBox comboDispositivoOut;
    private javax.swing.JComboBox comboDuracionSeñal;
    private javax.swing.JComboBox comboFrecuenciaMuestreo;
    private javax.swing.JComboBox comboResolucion;
    private javax.swing.JComboBox comboTipoSeñal;
    private javax.swing.JComboBox comboVentana;
    private javax.swing.JTextField comentario;
    private javax.swing.JTextField equipos;
    private javax.swing.JTextField finVentana;
    private javax.swing.JTextField freqFinal;
    private javax.swing.JTextField freqInicial;
    private javax.swing.JButton guardar;
    private javax.swing.JTextField inicioVentana;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private org.jdesktop.swingx.JXTaskPane jXTaskPane1;
    private org.jdesktop.swingx.JXTaskPane jXTaskPane2;
    private org.jdesktop.swingx.JXTaskPane jXTaskPane3;
    private org.jdesktop.swingx.JXTaskPane jXTaskPane4;
    private javax.swing.JButton medirSNRBoton;
    private javax.swing.JPanel nivelAmarillo1;
    private javax.swing.JPanel nivelAmarillo2;
    private javax.swing.JPanel nivelAmarillo3;
    private javax.swing.JPanel nivelRojo1;
    private javax.swing.JPanel nivelRojo2;
    private javax.swing.JPanel nivelRojo3;
    private javax.swing.JSlider nivelSalidaSlider;
    private javax.swing.JPanel nivelVerde1;
    private javax.swing.JPanel nivelVerde2;
    private javax.swing.JPanel nivelVerde3;
    private javax.swing.JPanel nivelVerde4;
    private javax.swing.JPanel nivelVerde5;
    private javax.swing.JPanel nivelVerde6;
    private javax.swing.JPanel nivelVerde7;
    private javax.swing.JPanel nivelVerde8;
    private javax.swing.JPanel panelNiveles;
    private javax.swing.JTextField repeticiones;
    private javax.swing.JButton salir;
    private javax.swing.JTextField stopMargin;
    private javax.swing.JTextField usuario;
    // End of variables declaration//GEN-END:variables

}
