/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package samdir_gui;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.FileWriter;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.LinkedHashMap;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Ana
 */
public class funcionDeTransf extends javax.swing.JFrame {
    
    String directory = ".archivos";
    String filename = "ventanaAjustes.os";
    LinkedHashMap hMapAjustes = new LinkedHashMap();
    /**
     * Creates new form funcionDeTransf
     */
    public funcionDeTransf() {
        initComponents();
        
       grupoOrdenFiltro.add(ordenEspecifico);
       grupoOrdenFiltro.add(ordenMinimo);
       grupoPlano.add(planoHorizontal);
       grupoPlano.add(planoVertical);
       grupoApertura.add(giroCompleto);
       grupoApertura.add(apertura);
       
        File file = new File(directory);
        if(!file.exists()){
            new File(directory).mkdir();
        }
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoOrdenFiltro = new javax.swing.ButtonGroup();
        grupoPlano = new javax.swing.ButtonGroup();
        grupoApertura = new javax.swing.ButtonGroup();
        jXTaskPane1 = new org.jdesktop.swingx.JXTaskPane();
        jLabel1 = new javax.swing.JLabel();
        resolucionDirectividad = new javax.swing.JComboBox();
        jPanel1 = new javax.swing.JPanel();
        planoHorizontal = new javax.swing.JRadioButton();
        planoVertical = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        giroCompleto = new javax.swing.JRadioButton();
        apertura = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        textAperturaInicial = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        textAperturaFinal = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jXTaskPane2 = new org.jdesktop.swingx.JXTaskPane();
        jPanel3 = new javax.swing.JPanel();
        Resolución = new javax.swing.JLabel();
        resolucionFiltro = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        tipoFiltro = new javax.swing.JComboBox();
        jPanel4 = new javax.swing.JPanel();
        ordenEspecifico = new javax.swing.JCheckBox();
        textOrdenFiltro = new javax.swing.JTextField();
        ordenMinimo = new javax.swing.JRadioButton();
        verFiltro = new javax.swing.JButton();
        jXTaskPane3 = new org.jdesktop.swingx.JXTaskPane();
        guardarResultados = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        directorioResultados = new javax.swing.JTextField();
        botonElegirDirectorio = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        botonAceptar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Samdir - Ajustes");
        getContentPane().setLayout(new org.jdesktop.swingx.VerticalLayout());

        jXTaskPane1.setTitle("Directividad");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Resolución angular");

        resolucionDirectividad.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "5", "10", "15", "30" }));
        resolucionDirectividad.setSelectedIndex(4);
        resolucionDirectividad.setName("resolucionDirectividad"); // NOI18N

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Plano", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 10), new java.awt.Color(51, 102, 255))); // NOI18N

        planoHorizontal.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        planoHorizontal.setSelected(true);
        planoHorizontal.setText("Horizontal");
        planoHorizontal.setName("planoHorizontal"); // NOI18N

        planoVertical.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        planoVertical.setText("Vertical");
        planoVertical.setName("planoVertical"); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(planoHorizontal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(planoVertical)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(planoHorizontal)
                    .addComponent(planoVertical)))
        );

        jPanel2.setPreferredSize(new java.awt.Dimension(270, 160));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/samdir_gui/directividadpeque.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 2, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Medición", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 10), new java.awt.Color(51, 102, 255))); // NOI18N
        jPanel6.setMinimumSize(new java.awt.Dimension(100, 50));

        giroCompleto.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        giroCompleto.setSelected(true);
        giroCompleto.setText("Giro Completo (360°)");

        apertura.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        apertura.setText("Apertura");
        apertura.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                aperturaStateChanged(evt);
            }
        });

        jLabel5.setText("inicio");

        textAperturaInicial.setEnabled(false);
        textAperturaInicial.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textAperturaInicialKeyTyped(evt);
            }
        });

        jLabel6.setText("°");

        jLabel7.setText("fin");

        textAperturaFinal.setEnabled(false);
        textAperturaFinal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textAperturaFinalKeyTyped(evt);
            }
        });

        jLabel8.setText("°");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(giroCompleto)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(apertura)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textAperturaInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textAperturaFinal, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(giroCompleto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(apertura)
                    .addComponent(jLabel5)
                    .addComponent(textAperturaInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(textAperturaFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addContainerGap())
        );

        javax.swing.GroupLayout jXTaskPane1Layout = new javax.swing.GroupLayout(jXTaskPane1.getContentPane());
        jXTaskPane1.getContentPane().setLayout(jXTaskPane1Layout);
        jXTaskPane1Layout.setHorizontalGroup(
            jXTaskPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jXTaskPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jXTaskPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jXTaskPane1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(resolucionDirectividad, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );
        jXTaskPane1Layout.setVerticalGroup(
            jXTaskPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jXTaskPane1Layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addGroup(jXTaskPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jXTaskPane1Layout.createSequentialGroup()
                        .addGroup(jXTaskPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(resolucionDirectividad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        getContentPane().add(jXTaskPane1);

        jXTaskPane2.setTitle("Análisis en Frecuencia");

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        Resolución.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Resolución.setText("Resolución");

        resolucionFiltro.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1/1 Octava", "1/3 Octava" }));
        resolucionFiltro.setName("resolucionFiltro"); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Tipo de Filtro");

        tipoFiltro.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "butter" }));
        tipoFiltro.setName("tipoFiltro"); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(Resolución, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(resolucionFiltro, 0, 86, Short.MAX_VALUE)
                    .addComponent(tipoFiltro, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Resolución)
                    .addComponent(resolucionFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tipoFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Orden del Filtro", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 10), new java.awt.Color(51, 102, 255))); // NOI18N

        ordenEspecifico.setSelected(true);
        ordenEspecifico.setText("Orden específico");
        ordenEspecifico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ordenEspecificoActionPerformed(evt);
            }
        });

        textOrdenFiltro.setText("10");
        textOrdenFiltro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textOrdenFiltroKeyTyped(evt);
            }
        });

        ordenMinimo.setText("Orden mínimo");
        ordenMinimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ordenMinimoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(ordenEspecifico)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(textOrdenFiltro, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(ordenMinimo)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ordenEspecifico)
                    .addComponent(textOrdenFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ordenMinimo)
                .addContainerGap())
        );

        verFiltro.setText("Ver");
        verFiltro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verFiltroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jXTaskPane2Layout = new javax.swing.GroupLayout(jXTaskPane2.getContentPane());
        jXTaskPane2.getContentPane().setLayout(jXTaskPane2Layout);
        jXTaskPane2Layout.setHorizontalGroup(
            jXTaskPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jXTaskPane2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(verFiltro, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
                .addContainerGap())
        );
        jXTaskPane2Layout.setVerticalGroup(
            jXTaskPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jXTaskPane2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jXTaskPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(verFiltro)
                    .addGroup(jXTaskPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        getContentPane().add(jXTaskPane2);

        jXTaskPane3.setTitle("Resultados");

        guardarResultados.setBackground(new java.awt.Color(214, 223, 247));
        guardarResultados.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        guardarResultados.setText("Guardar respuesta impulsiva");
        guardarResultados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarResultadosActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Directorio: ");

        directorioResultados.setEnabled(false);
        directorioResultados.setName("directorioResultados"); // NOI18N

        botonElegirDirectorio.setText(". . . ");
        botonElegirDirectorio.setEnabled(false);
        botonElegirDirectorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonElegirDirectorioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jXTaskPane3Layout = new javax.swing.GroupLayout(jXTaskPane3.getContentPane());
        jXTaskPane3.getContentPane().setLayout(jXTaskPane3Layout);
        jXTaskPane3Layout.setHorizontalGroup(
            jXTaskPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jXTaskPane3Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jXTaskPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jXTaskPane3Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(directorioResultados, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(botonElegirDirectorio))
                    .addComponent(guardarResultados))
                .addContainerGap(72, Short.MAX_VALUE))
        );
        jXTaskPane3Layout.setVerticalGroup(
            jXTaskPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jXTaskPane3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(guardarResultados)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jXTaskPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(directorioResultados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonElegirDirectorio)))
        );

        getContentPane().add(jXTaskPane3);

        jPanel5.setMinimumSize(new java.awt.Dimension(100, 50));
        jPanel5.setPreferredSize(new java.awt.Dimension(500, 50));

        botonAceptar.setText("Aceptar");
        botonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAceptarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(389, Short.MAX_VALUE)
                .addComponent(botonAceptar)
                .addGap(51, 51, 51))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(botonAceptar)
                .addContainerGap())
        );

        getContentPane().add(jPanel5);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void guardarResultadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarResultadosActionPerformed
        // TODO add your handling code here:
        if(guardarResultados.isSelected() == true) {
            botonElegirDirectorio.setEnabled(true);
            directorioResultados.setEnabled(true);
        }
        else{
            botonElegirDirectorio.setEnabled(false);
            directorioResultados.setEnabled(false);
        }
    }//GEN-LAST:event_guardarResultadosActionPerformed

    private void botonElegirDirectorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonElegirDirectorioActionPerformed
        // TODO add your handling code here:
        try{
        JFileChooser file = new JFileChooser();
        int resp = file.showSaveDialog(this);
        File guarda =file.getSelectedFile();
        String directorio = "";
            if(guarda !=null){
                //Elegir el formato (guarda+".txt")
                FileWriter save =new FileWriter(guarda);
                //Aca debería poner lo que quiero guardar en el archivo
                //save.write(directorioResultados.getText());
             //   save.close();
                if (resp==JFileChooser.APPROVE_OPTION) {
                    JOptionPane.showMessageDialog(null,file.getSelectedFile().toString());
                    directorioResultados.setText(guarda.getPath());
                    directorio = directorioResultados.getText();
                } else if (resp==JFileChooser.CANCEL_OPTION) {
                    directorio = directorioResultados.getText();
                    JOptionPane.showMessageDialog(null,"Se pulsó la opción Cancelar");           
                }
                 
            }
           
        }
        catch(IOException ex)
        {
            JOptionPane.showMessageDialog(null,
              "Su archivo no se ha guardado",
                 "Advertencia",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_botonElegirDirectorioActionPerformed

    private void ordenMinimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ordenMinimoActionPerformed
        // TODO add your handling code here:
        textOrdenFiltro.setEnabled(false);
    }//GEN-LAST:event_ordenMinimoActionPerformed

    private void ordenEspecificoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ordenEspecificoActionPerformed
        // TODO add your handling code here:
        textOrdenFiltro.setEnabled(true);
    }//GEN-LAST:event_ordenEspecificoActionPerformed

    private void botonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAceptarActionPerformed
        // TODO add your handling code here:
        if(checkOrdenFiltro()){
            cargarDatos();
            botonAceptarAjustesCls.setTrigger(evt.getActionCommand());
        }
        
    }//GEN-LAST:event_botonAceptarActionPerformed

    private void verFiltroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verFiltroActionPerformed
        // TODO add your handling code here:
        if(checkOrdenFiltro()){
            cargarDatos();
            botonAceptarAjustesCls.setTrigger(evt.getActionCommand());
        }
        
    }//GEN-LAST:event_verFiltroActionPerformed
    private boolean checkOrdenFiltro(){
    String orden = textOrdenFiltro.getText();
    int ordenNumero = Integer.parseInt(orden);
        
        if((!orden.isEmpty())){
            if(ordenNumero == 0){
                JOptionPane.showMessageDialog(null, "Caracter Invalido");
                return false;
            }else{
                if(ordenNumero > 20){
                    JOptionPane.showMessageDialog(null, "Filtros Menores a Orden 20");
                    return false;
                }else{
                    if(ordenNumero%2 != 0){
                        JOptionPane.showMessageDialog(null, "Solo se aceptan filtros de orden par");
                        return false;}
                    else
                        return true;
                }
            }
        }
        return true;    
    }
    
    
    private void textOrdenFiltroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textOrdenFiltroKeyTyped
        // TODO add your handling code here:
        char car = evt.getKeyChar();
        if(textOrdenFiltro.getText().length()>=2) 
            evt.consume();
        if((car<'0' || car>'9')) 
            evt.consume();
    }//GEN-LAST:event_textOrdenFiltroKeyTyped

    private void textAperturaInicialKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textAperturaInicialKeyTyped
        // TODO add your handling code here:
         char car = evt.getKeyChar();
        if(textAperturaInicial.getText().length()>=3) 
            evt.consume();
        if((car<'0' || car>'9')) 
            evt.consume();
    }//GEN-LAST:event_textAperturaInicialKeyTyped

    private void textAperturaFinalKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textAperturaFinalKeyTyped
        // TODO add your handling code here:
                 char car = evt.getKeyChar();
        if(textAperturaFinal.getText().length()>=3) 
            evt.consume();
        if((car<'0' || car>'9')) 
            evt.consume();
    }//GEN-LAST:event_textAperturaFinalKeyTyped

    private void aperturaStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_aperturaStateChanged
        // TODO add your handling code here:
        if(apertura.isSelected() == true){
            textAperturaInicial.setEnabled(true);
            textAperturaFinal.setEnabled(true);
        }
        else{
            textAperturaInicial.setEnabled(false);
            textAperturaFinal.setEnabled(false);
        }
    }//GEN-LAST:event_aperturaStateChanged

    private void cargarDatos(){
        hMapAjustes.put(resolucionDirectividad.getName(), Integer.valueOf(resolucionDirectividad.getSelectedItem().toString()));
        if(planoHorizontal.isSelected() == true)
            hMapAjustes.put("planoDirectividad", "planoHorizontal");
        else
            hMapAjustes.put("planoDirectividad", "planoVertical");
        hMapAjustes.put(resolucionFiltro.getName(), resolucionFiltro.getSelectedItem().toString());
        hMapAjustes.put(tipoFiltro.getName(), tipoFiltro.getSelectedItem().toString());
        if(ordenMinimo.isSelected() == true)
            hMapAjustes.put("ordenFiltro", Integer.valueOf("2"));
        else
            hMapAjustes.put("ordenFiltro", Integer.valueOf(textOrdenFiltro.getText()));
        
        if(guardarResultados.isSelected() == true)
            hMapAjustes.put("guardarResultados", Integer.valueOf("1"));
        else
            hMapAjustes.put("guardarResultados", Integer.valueOf("0"));
        if(giroCompleto.isSelected() == true){
            hMapAjustes.put("medicionInicial", Integer.valueOf("0"));
            hMapAjustes.put("medicionFinal", Integer.valueOf("360"));
        }
        else{
            hMapAjustes.put("medicionInicial", Integer.valueOf(textAperturaInicial.getText()));
            hMapAjustes.put("medicionFinal", Integer.valueOf(textAperturaFinal.getText()));
        }
        hMapAjustes.put(directorioResultados.getName(), directorioResultados.getText());
        WriterObject(hMapAjustes);
    }
    
    public void WriterObject(Object obj){
        try{
            String strFilename = directory + "\\" + filename;
               FileOutputStream fileOut = new FileOutputStream(strFilename);
	       ObjectOutputStream out = new ObjectOutputStream(fileOut);
	       out.writeObject(obj);
	       out.close();
        }catch(IOException ex){
            ex.printStackTrace();
        }
    }
    
    public Object ReadObject() {
    Object obj = null;
    String strFilename = directory + "\\" + filename;

        try {
            File file = new File(strFilename);
         // Read object only if file exist
            if (file.exists()) {
                ObjectInputStream in = new ObjectInputStream(new
                FileInputStream(strFilename));
		obj = in.readObject();
		in.close();
            }
	}catch (IOException ex) {
		ex.printStackTrace();
	}catch (ClassNotFoundException cexp) {
		cexp.printStackTrace();
	}

    return obj;
    }
    /**
     * @param args the command line arguments
     
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(funcionDeTransf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(funcionDeTransf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(funcionDeTransf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(funcionDeTransf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
*/
        /* Create and display the form 
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new funcionDeTransf().setVisible(true);
            }
        });
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Resolución;
    private javax.swing.JRadioButton apertura;
    private javax.swing.JButton botonAceptar;
    private javax.swing.JButton botonElegirDirectorio;
    private javax.swing.JTextField directorioResultados;
    private javax.swing.JRadioButton giroCompleto;
    private javax.swing.ButtonGroup grupoApertura;
    private javax.swing.ButtonGroup grupoOrdenFiltro;
    private javax.swing.ButtonGroup grupoPlano;
    private javax.swing.JCheckBox guardarResultados;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private org.jdesktop.swingx.JXTaskPane jXTaskPane1;
    private org.jdesktop.swingx.JXTaskPane jXTaskPane2;
    private org.jdesktop.swingx.JXTaskPane jXTaskPane3;
    private javax.swing.JCheckBox ordenEspecifico;
    private javax.swing.JRadioButton ordenMinimo;
    private javax.swing.JRadioButton planoHorizontal;
    private javax.swing.JRadioButton planoVertical;
    private javax.swing.JComboBox resolucionDirectividad;
    private javax.swing.JComboBox resolucionFiltro;
    private javax.swing.JTextField textAperturaFinal;
    private javax.swing.JTextField textAperturaInicial;
    private javax.swing.JTextField textOrdenFiltro;
    private javax.swing.JComboBox tipoFiltro;
    private javax.swing.JButton verFiltro;
    // End of variables declaration//GEN-END:variables
}
